spring:
  datasource:
    url: jdbc:mysql://localhost:3306/joblistingdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081


logging:
  level:
    com.site.joblisting: INFO